// pages/api/generate-pdf.js
// ─────────────────────────────────────────────────────────────────────────────
// Generates a styled PDF for Client Report or Attorney Memo.
// Called after AI report generation + Stripe payment confirmation.
//
// POST /api/generate-pdf
// Body: { type: "report" | "memo", mark, goods, data (the parsed AI report) }
// Returns: PDF binary (application/pdf)
// ─────────────────────────────────────────────────────────────────────────────

import PDFDocument from "pdfkit";

// ── Color palette ──────────────────────────────────────────────────────────

const COLORS = {
  navy: "#0f1e3c",
  gold: "#c9a84c",
  green: "#2d7a4f",
  red: "#c0392b",
  orange: "#e67e22",
  darkText: "#1a2e23",
  bodyText: "#333333",
  lightText: "#6b8a78",
  muted: "#888888",
  bg: "#f8faf9",
  white: "#ffffff",
  border: "#d4e3d9",
};

function riskColor(level) {
  const l = (level || "").toUpperCase();
  if (l === "HIGH") return COLORS.red;
  if (l === "MEDIUM") return COLORS.orange;
  return COLORS.green;
}

// ── PDF helpers ────────────────────────────────────────────────────────────

function drawHeader(doc, mark, type) {
  // Navy header bar
  doc.rect(0, 0, doc.page.width, 80).fill(COLORS.navy);

  // Logo
  doc.fontSize(20).font("Helvetica-Bold").fillColor(COLORS.white)
    .text("MarkItNow", 50, 28, { continued: true })
    .fillColor(COLORS.gold).text(".ai", { continued: false });

  // Report type badge
  const badge = type === "report" ? "CLIENT REPORT" : "ATTORNEY MEMO";
  doc.fontSize(9).font("Helvetica-Bold").fillColor(COLORS.gold)
    .text(badge, doc.page.width - 200, 34, { width: 150, align: "right" });

  doc.moveDown(2);
  doc.y = 100;

  // Mark name
  doc.fontSize(24).font("Helvetica-Bold").fillColor(COLORS.navy)
    .text(`"${mark}"`, 50, doc.y, { width: doc.page.width - 100 });
  doc.moveDown(0.3);

  // Subtitle
  doc.fontSize(10).font("Helvetica").fillColor(COLORS.muted)
    .text(`${type === "report" ? "Trademark Conflict Analysis" : "Trademark Registrability Memorandum"} · Generated ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`, 50);
  doc.moveDown(1);

  // Divider
  doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y)
    .strokeColor(COLORS.border).lineWidth(1).stroke();
  doc.moveDown(1);
}

function sectionTitle(doc, text, color = COLORS.navy) {
  doc.fontSize(13).font("Helvetica-Bold").fillColor(color).text(text, 50, doc.y, { width: doc.page.width - 100 });
  doc.moveDown(0.4);
}

function bodyText(doc, text) {
  doc.fontSize(10).font("Helvetica").fillColor(COLORS.bodyText)
    .text(text, 50, doc.y, { width: doc.page.width - 100, lineGap: 3 });
  doc.moveDown(0.6);
}

function bulletPoint(doc, title, description, accentColor = COLORS.navy) {
  const startY = doc.y;
  // Bullet dot
  doc.circle(58, startY + 5, 3).fill(accentColor);

  // Title
  doc.fontSize(10).font("Helvetica-Bold").fillColor(COLORS.darkText)
    .text(title, 68, startY, { width: doc.page.width - 130 });

  // Description
  if (description) {
    doc.fontSize(9).font("Helvetica").fillColor(COLORS.bodyText)
      .text(description, 68, doc.y, { width: doc.page.width - 130, lineGap: 2 });
  }
  doc.moveDown(0.5);
}

function checkNewPage(doc, needed = 100) {
  if (doc.y + needed > doc.page.height - 80) {
    doc.addPage();
    doc.y = 50;
  }
}

function drawFooter(doc) {
  const y = doc.page.height - 50;
  doc.moveTo(50, y).lineTo(doc.page.width - 50, y)
    .strokeColor(COLORS.border).lineWidth(0.5).stroke();

  doc.fontSize(7).font("Helvetica").fillColor(COLORS.muted)
    .text(
      "This report is generated by AI and does not constitute legal advice. For legal guidance, consult a licensed trademark attorney. © 2026 MarkItNow.ai",
      50, y + 8,
      { width: doc.page.width - 100, align: "center" }
    );
}

// ── Client Report PDF ──────────────────────────────────────────────────────

function buildClientReport(doc, mark, goods, data) {
  drawHeader(doc, mark, "report");

  // Score box
  const score = data.clientConfidenceScore || 50;
  const risk = (data.overallRiskLevel || "MEDIUM").toUpperCase();
  const scoreCol = riskColor(risk);

  doc.roundedRect(50, doc.y, doc.page.width - 100, 70, 8)
    .fillAndStroke("#f0f7f2", COLORS.border);

  doc.fontSize(9).font("Helvetica-Bold").fillColor(COLORS.lightText)
    .text("CONFIDENCE SCORE", 70, doc.y - 60, { width: 100 });
  doc.fontSize(32).font("Helvetica-Bold").fillColor(scoreCol)
    .text(`${score}`, 70, doc.y - 48);
  doc.fontSize(9).font("Helvetica-Bold").fillColor(scoreCol)
    .text(`RISK: ${risk}`, 70, doc.y - 14);

  doc.fontSize(9).font("Helvetica-Bold").fillColor(COLORS.lightText)
    .text("EXECUTIVE SUMMARY", 180, doc.y - 60, { width: doc.page.width - 250 });
  doc.fontSize(10).font("Helvetica").fillColor(COLORS.bodyText)
    .text(data.executiveSummary || "", 180, doc.y - 48, { width: doc.page.width - 250, lineGap: 2 });

  doc.y = doc.y + 20;
  doc.moveDown(1);

  // Why it could work
  if (data.whyItCouldWork?.length > 0) {
    checkNewPage(doc, 120);
    sectionTitle(doc, "Why It Could Work", COLORS.green);
    for (const item of data.whyItCouldWork) {
      checkNewPage(doc, 60);
      bulletPoint(doc, item.reason, item.explanation, COLORS.green);
      if (item.legalHook) {
        doc.fontSize(8).font("Helvetica-Oblique").fillColor(COLORS.lightText)
          .text(item.legalHook, 68, doc.y, { width: doc.page.width - 130 });
        doc.moveDown(0.4);
      }
    }
    doc.moveDown(0.5);
  }

  // Why it might not work
  if (data.whyItMightNotWork?.length > 0) {
    checkNewPage(doc, 120);
    sectionTitle(doc, "Potential Risks", COLORS.red);
    for (const item of data.whyItMightNotWork) {
      checkNewPage(doc, 60);
      bulletPoint(doc, item.reason, item.explanation, COLORS.red);
      if (item.legalHook) {
        doc.fontSize(8).font("Helvetica-Oblique").fillColor(COLORS.lightText)
          .text(item.legalHook, 68, doc.y, { width: doc.page.width - 130 });
        doc.moveDown(0.4);
      }
    }
    doc.moveDown(0.5);
  }

  // Conflict snapshot
  if (data.conflictSnapshot?.length > 0) {
    checkNewPage(doc, 150);
    sectionTitle(doc, "Key Conflicts Found");

    // Table header
    const tableLeft = 50;
    const tableWidth = doc.page.width - 100;
    doc.rect(tableLeft, doc.y, tableWidth, 22).fill("#eef2f0");
    doc.fontSize(8).font("Helvetica-Bold").fillColor(COLORS.navy);
    doc.text("MARK", tableLeft + 8, doc.y + 6, { width: 140 });
    doc.text("OWNER", tableLeft + 150, doc.y - 10, { width: 130 });
    doc.text("CLASS", tableLeft + 290, doc.y - 10, { width: 40 });
    doc.text("RISK", tableLeft + 340, doc.y - 10, { width: 50 });
    doc.text("REASON", tableLeft + 390, doc.y - 10, { width: tableWidth - 400 });
    doc.y = doc.y + 6;
    doc.moveDown(0.3);

    for (const conflict of data.conflictSnapshot) {
      checkNewPage(doc, 35);
      const rowY = doc.y;

      doc.fontSize(9).font("Helvetica-Bold").fillColor(COLORS.darkText)
        .text(conflict.markName || "", tableLeft + 8, rowY, { width: 138 });
      doc.fontSize(8).font("Helvetica").fillColor(COLORS.bodyText)
        .text(conflict.owner || "", tableLeft + 150, rowY, { width: 130 });
      doc.text(String(conflict.class || ""), tableLeft + 290, rowY, { width: 40 });
      doc.font("Helvetica-Bold").fillColor(riskColor(conflict.risk))
        .text(conflict.risk || "", tableLeft + 340, rowY, { width: 50 });
      doc.font("Helvetica").fillColor(COLORS.bodyText)
        .text(conflict.reason || "", tableLeft + 390, rowY, { width: tableWidth - 400 });

      doc.y = Math.max(doc.y, rowY + 14);
      doc.moveDown(0.3);

      // Row divider
      doc.moveTo(tableLeft, doc.y).lineTo(tableLeft + tableWidth, doc.y)
        .strokeColor("#eef2f0").lineWidth(0.5).stroke();
      doc.moveDown(0.3);
    }
    doc.moveDown(0.5);
  }

  // Next steps
  if (data.whatHappensNext) {
    checkNewPage(doc, 80);
    sectionTitle(doc, "Recommended Next Steps");
    bodyText(doc, data.whatHappensNext);
  }

  drawFooter(doc);
}

// ── Attorney Memo PDF ──────────────────────────────────────────────────────

function buildAttorneyMemo(doc, mark, goods, data) {
  drawHeader(doc, mark, "memo");

  // Memo summary
  if (data.memoSummary) {
    doc.roundedRect(50, doc.y, doc.page.width - 100, 0, 8); // placeholder
    sectionTitle(doc, "Memorandum Summary");
    bodyText(doc, data.memoSummary);
    doc.moveDown(0.5);
  }

  // Why it could work (legal arguments)
  if (data.whyItCouldWork?.length > 0) {
    checkNewPage(doc, 120);
    sectionTitle(doc, "Arguments Supporting Registrability", COLORS.green);
    for (const item of data.whyItCouldWork) {
      checkNewPage(doc, 80);
      bulletPoint(doc, item.argument, item.analysis, COLORS.green);
      if (item.citations?.length > 0) {
        doc.fontSize(8).font("Helvetica-Oblique").fillColor(COLORS.lightText)
          .text(`Citations: ${item.citations.join("; ")}`, 68, doc.y, { width: doc.page.width - 130 });
        doc.moveDown(0.4);
      }
    }
    doc.moveDown(0.5);
  }

  // Why it might not work
  if (data.whyItMightNotWork?.length > 0) {
    checkNewPage(doc, 120);
    sectionTitle(doc, "Potential Obstacles", COLORS.red);
    for (const item of data.whyItMightNotWork) {
      checkNewPage(doc, 80);
      bulletPoint(doc, item.obstacle, item.analysis, COLORS.red);
      if (item.citations?.length > 0) {
        doc.fontSize(8).font("Helvetica-Oblique").fillColor(COLORS.lightText)
          .text(`Citations: ${item.citations.join("; ")}`, 68, doc.y, { width: doc.page.width - 130 });
        doc.moveDown(0.4);
      }
    }
    doc.moveDown(0.5);
  }

  // DuPont Analysis
  if (data.duPontAnalysis) {
    checkNewPage(doc, 200);
    sectionTitle(doc, "DuPont 13-Factor Analysis");

    if (data.duPontAnalysis.overview) {
      doc.fontSize(9).font("Helvetica-Oblique").fillColor(COLORS.bodyText)
        .text(data.duPontAnalysis.overview, 50, doc.y, { width: doc.page.width - 100, lineGap: 2 });
      doc.moveDown(0.8);
    }

    for (const factor of data.duPontAnalysis.factors || []) {
      checkNewPage(doc, 80);

      // Factor number circle
      const circleY = doc.y + 5;
      doc.circle(60, circleY, 8).fill(COLORS.navy);
      doc.fontSize(8).font("Helvetica-Bold").fillColor(COLORS.white)
        .text(String(factor.number), 55, circleY - 4, { width: 10, align: "center" });

      // Factor name + finding
      const findingColor = factor.finding === "FAVORABLE" ? COLORS.green
        : factor.finding === "UNFAVORABLE" ? COLORS.red : COLORS.muted;

      doc.fontSize(10).font("Helvetica-Bold").fillColor(COLORS.darkText)
        .text(factor.factor, 78, doc.y, { width: doc.page.width - 200, continued: true })
        .fontSize(9).font("Helvetica-Bold").fillColor(findingColor)
        .text(`  [${factor.finding}]`, { continued: false });

      // Analysis
      doc.fontSize(9).font("Helvetica").fillColor(COLORS.bodyText)
        .text(factor.analysis, 78, doc.y, { width: doc.page.width - 140, lineGap: 2 });
      doc.moveDown(0.6);
    }
    doc.moveDown(0.5);
  }

  // Prosecution Strategy
  if (data.prosecutionStrategy?.length > 0) {
    checkNewPage(doc, 120);
    sectionTitle(doc, "Prosecution Strategy");
    for (const item of data.prosecutionStrategy) {
      checkNewPage(doc, 60);
      bulletPoint(doc, item.action, item.rationale, COLORS.gold);
      if (item.citation) {
        doc.fontSize(8).font("Helvetica-Oblique").fillColor(COLORS.lightText)
          .text(item.citation, 68, doc.y, { width: doc.page.width - 130 });
        doc.moveDown(0.3);
      }
    }
    doc.moveDown(0.5);
  }

  // Risk Matrix
  if (data.riskMatrix?.length > 0) {
    checkNewPage(doc, 150);
    sectionTitle(doc, "Risk Matrix");

    const tableLeft = 50;
    const tableWidth = doc.page.width - 100;

    // Header
    doc.rect(tableLeft, doc.y, tableWidth, 20).fill("#eef2f0");
    doc.fontSize(8).font("Helvetica-Bold").fillColor(COLORS.navy);
    doc.text("RISK", tableLeft + 8, doc.y + 5, { width: 180 });
    doc.text("LIKELIHOOD", tableLeft + 200, doc.y - 11, { width: 70 });
    doc.text("SEVERITY", tableLeft + 280, doc.y - 11, { width: 70 });
    doc.text("MITIGATION", tableLeft + 360, doc.y - 11, { width: tableWidth - 370 });
    doc.y += 10;
    doc.moveDown(0.3);

    for (const r of data.riskMatrix) {
      checkNewPage(doc, 40);
      const rowY = doc.y;

      doc.fontSize(9).font("Helvetica-Bold").fillColor(COLORS.darkText)
        .text(r.risk, tableLeft + 8, rowY, { width: 180 });
      doc.fontSize(8).font("Helvetica-Bold").fillColor(riskColor(r.likelihood))
        .text(r.likelihood, tableLeft + 200, rowY, { width: 70 });
      doc.fontSize(8).font("Helvetica-Bold").fillColor(riskColor(r.severity))
        .text(r.severity, tableLeft + 280, rowY, { width: 70 });
      doc.fontSize(8).font("Helvetica").fillColor(COLORS.bodyText)
        .text(r.mitigation, tableLeft + 360, rowY, { width: tableWidth - 370 });

      doc.y = Math.max(doc.y, rowY + 14);
      doc.moveDown(0.3);
      doc.moveTo(tableLeft, doc.y).lineTo(tableLeft + tableWidth, doc.y)
        .strokeColor("#eef2f0").lineWidth(0.5).stroke();
      doc.moveDown(0.3);
    }
    doc.moveDown(0.5);
  }

  // Overall assessment
  if (data.overallLegalAssessment || data.proceedRationale) {
    checkNewPage(doc, 100);
    sectionTitle(doc, "Overall Legal Assessment");

    if (data.overallLegalAssessment) {
      const assessColor = riskColor(data.overallLegalAssessment);
      doc.fontSize(14).font("Helvetica-Bold").fillColor(assessColor)
        .text(`Risk Level: ${data.overallLegalAssessment}`, 50, doc.y, { width: doc.page.width - 100 });
      doc.moveDown(0.3);

      doc.fontSize(10).font("Helvetica-Bold").fillColor(COLORS.darkText)
        .text(`Recommendation: ${data.recommendProceed ? "Proceed with filing" : "Exercise caution"}`, 50, doc.y, { width: doc.page.width - 100 });
      doc.moveDown(0.5);
    }

    if (data.proceedRationale) {
      bodyText(doc, data.proceedRationale);
    }
  }

  drawFooter(doc);
}

// ── API Handler ────────────────────────────────────────────────────────────

export default async function handler(req, res) {
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });

  const { type, mark, goods, data } = req.body;

  if (!type || !mark || !data) {
    return res.status(400).json({ error: "type, mark, and data are required" });
  }

  try {
    const doc = new PDFDocument({
      size: "letter",
      margins: { top: 50, bottom: 60, left: 50, right: 50 },
      info: {
        Title: `${type === "report" ? "Client Report" : "Attorney Memo"} - "${mark}"`,
        Author: "MarkItNow.ai",
        Subject: `Trademark Analysis for "${mark}"`,
        Creator: "MarkItNow.ai",
      },
    });

    // Collect PDF into buffer
    const chunks = [];
    doc.on("data", (chunk) => chunks.push(chunk));

    const pdfReady = new Promise((resolve) => {
      doc.on("end", () => resolve(Buffer.concat(chunks)));
    });

    // Build the PDF
    if (type === "report") {
      buildClientReport(doc, mark, goods, data);
    } else {
      buildAttorneyMemo(doc, mark, goods, data);
    }

    doc.end();
    const pdfBuffer = await pdfReady;

    // Send PDF response
    const filename = `MarkItNow-${type === "report" ? "Report" : "Memo"}-${mark.replace(/[^a-zA-Z0-9]/g, "_")}.pdf`;

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
    res.setHeader("Content-Length", pdfBuffer.length);
    res.send(pdfBuffer);
  } catch (err) {
    console.error("PDF generation error:", err);
    return res.status(500).json({ error: err.message });
  }
}
