// pages/api/memo-draft.js
// Lightweight memo drafter - takes existing analysis report, returns memo
// Called AFTER analysis-agent completes on the frontend

export const config = {
  maxDuration: 60, // seconds - requires Vercel Pro, falls back gracefully on free tier
};

const ANTHROPIC_API = "https://api.anthropic.com/v1/messages";
const MODEL = "claude-sonnet-4-20250514";

export default async function handler(req, res) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
  if (req.method === "OPTIONS") return res.status(200).end();
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });

  const { mark, goodsServices, report } = req.body;
  if (!mark?.trim()) return res.status(400).json({ error: "mark is required" });
  if (!report) return res.status(400).json({ error: "report is required" });

  const anthropicKey = process.env.NEXT_PUBLIC_ANTHROPIC_KEY;
  if (!anthropicKey) return res.status(500).json({ error: "ANTHROPIC_KEY not configured" });

  const conflicts = report.scoring?.scoredConflicts || [];
  const highRisk = conflicts.filter(c => c.riskScore === "HIGH");
  const medRisk = conflicts.filter(c => c.riskScore === "MEDIUM");

  const conflictSummary = conflicts.slice(0, 3).map((c, i) =>
    `[${i+1}] "${c.markName}" (Serial: ${c.serialNumber || "N/A"}) | Owner: ${c.owner} | Status: ${c.status} | Risk: ${c.riskScore} | Reasoning: ${c.riskReasoning || "N/A"}`
  ).join("\n");

  const prompt = `You are a trademark attorney AI drafting a legal memorandum.

MARK: "${mark}"
GOODS/SERVICES: ${goodsServices || "Not specified"}
DATE: ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}

ANALYSIS RESULTS:
- Overall Risk: ${report.scoring?.overallRisk}
- Total Conflicts: ${report.retrieval?.totalFound || 0}
- Active Conflicts: ${report.retrieval?.activeCount || 0}
- High Risk: ${highRisk.length} | Medium Risk: ${medRisk.length}
- Registrability: ${report.analysis?.registrabilityAssessment?.likelihood}
- Recommendation: ${report.analysis?.recommendation?.action}
- Executive Summary: ${report.analysis?.executiveSummary}

TOP CONFLICTS:
${conflictSummary || "None found."}

Write a concise legal memorandum. Cite serial numbers. Do not fabricate data not shown above.
Label all output as AI-generated. Do not claim to be attorney work product.

Respond ONLY in valid JSON:
{
  "memo": {
    "header": {
      "to": "Client",
      "from": "MarkItNow.ai Legal Analysis",
      "re": "Trademark Clearance Analysis for '${mark}'",
      "date": "${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}",
      "confidentiality": "AI-Generated Legal Analysis - Not Attorney Work Product"
    },
    "executiveSummary": "string (2-3 paragraphs)",
    "sectionI": { "title": "I. BACKGROUND", "content": "string" },
    "sectionII": { "title": "II. SEARCH RESULTS", "content": "string" },
    "sectionIII": {
      "title": "III. LIKELIHOOD OF CONFUSION ANALYSIS",
      "subsections": [
        { "factor": "string", "analysis": "string", "weight": "FAVORS_APPLICANT|FAVORS_REGISTRANT|NEUTRAL" }
      ],
      "overallConclusion": "string"
    },
    "sectionIV": { "title": "IV. REGISTRABILITY", "content": "string" },
    "sectionV": {
      "title": "V. RISK BY CONFLICT",
      "conflicts": [
        { "markName": "string", "serialNumber": "string", "riskLevel": "HIGH|MEDIUM|LOW", "analysis": "string" }
      ]
    },
    "sectionVI": {
      "title": "VI. CONCLUSION",
      "conclusion": "string",
      "recommendations": ["string"],
      "filingStrategy": "string"
    },
    "disclaimer": "This memorandum was generated by artificial intelligence and is provided for informational purposes only. It does not constitute legal advice and does not create an attorney-client relationship. Consult a licensed trademark attorney for advice specific to your situation."
  }
}`;

  try {
    const response = await fetch(ANTHROPIC_API, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": anthropicKey,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: MODEL,
        max_tokens: 2000,
        temperature: 0.2,
        system: "You are a trademark attorney AI drafting legal memos. Cite only real data provided. Never fabricate. Clearly label output as AI-generated. Respond only in valid JSON.",
        messages: [{ role: "user", content: prompt }],
      }),
    });

    const data = await response.json();
    if (data.error) return res.status(500).json({ error: data.error.message });

    const text = data.content?.find(b => b.type === "text")?.text || "{}";
    const result = JSON.parse(text.replace(/```json|```/g, "").trim());
    return res.status(200).json(result);
  } catch (err) {
    console.error("[memo-draft] error:", err);
    return res.status(500).json({ error: err.message });
  }
}
